apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3   # number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    tolerations:
      - key: "mykey"
        operator: Equal
        value: "myvalue"
        effect: "NoSchedule"
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80