apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-db
spec:
  crVersion: 1.14.0

  secretsName: my-db-secrets

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0

    volumeSpec:   # 🔥 REQUIRED
      persistentVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: college-nfs-stateful
        resources:
          requests:
            storage: 1Gi