apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deploy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sql-app
  template:
    metadata:
      labels:
        app: sql-app
    spec:
      containers:
        - image: mysql:8.0
          name: sql-cont
          ports:
            - containerPort: 3306   
          env:
                - name: MYSQL_ROOT_PASSWORD
                  value: "Root@123"
          envFrom:
            - configMapRef:
                name:  app-config
              
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          volumeMounts:
            
            - name: sql-volume
              mountPath: /var/lib/mysql

            
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql

      volumes:
        - name: sql-volume
          persistentVolumeClaim:
            claimName: college-pvc
        - name: init-script
          configMap:
            name: mysql-init-script

---
apiVersion: v1
kind: Service
metadata:
  name: maria-db
spec:
  selector:
    app: sql-app
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306