apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxvalues.maxSurge }}
      maxUnavailable: {{ .Values.maxvalues.maxUnavailable }}
  selector:
    matchLabels:
      app: college-app
  template:
    metadata:
      labels:
        app: college-app
    spec:
      containers:
        - name: college-cont
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: app-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app-service.name }}
spec:
  selector:
    app: college-app
  type: ClusterIP
  ports:
    - port: {{ .Values.app-service.port }}
      targetPort: {{ .Values.app-service.targetPort }}