apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-deploy
spec:
  replicas: {{ .Values.sql.replicaCount }}
  minReadySeconds:  10
  serviceName: {{ .Values.sql.serviceName }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: sql-app
  template:
    metadata:
      labels:
        app: sql-app
    spec:
      terminationGracePeriodSeconds:  10
      containers:
        - image: {{ .Values.sql.image.name }}:{{ .Values.sql.image.tag }}
          imagePullPolicy: {{ .Values.sql.image.pullPolicy }}
          name: sql-cont
          ports:
            - containerPort: {{ .Values.sql.ports.containerPort }}
          env:
                - name: MARIADB_ROOT_PASSWORD
                  value: "Root@123"
          envFrom:
            - configMapRef:
                name:  app-config
              
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          volumeMounts:
            - name: sql-v
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              
      volumes:
        - name: init-script
          configMap:
            name: mysql-init-script

  volumeClaimTemplates:
    - metadata:
        name: sql-v
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.sql.volume.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.sql.volume.storage }}

      

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sql-service.name }}
spec:
  selector:
    app: sql-app
  clusterIP:  None
  ports:
    - port: {{ .Values.sql-service.port }}
      targetPort: {{ .Values.sql-service.targetPort }}